sudo: false
language: python
python:
  - 3.3
  - 3.4
  - 3.5
  - 3.6
#os:
#  - linux
#  - osx
#osx_image: xcode8

addons:
  apt:
    packages:
      - libtool
      # - libtool-bin # is only required for Ubuntu 16.04/Debian Jessie and newer.
      - autoconf
      - automake
      - cmake
      - g++
      - pkg-config
      - unzip

install:
  - curl -sL git.io/v18DU | bash
  - git clone --depth 1 --single-branch -b ci-test https://github.com/lambdalisue/neovim-prompt ci-test
  - pip install coveralls

script:
  - cd ci-test
  - PATH="$HOME/neovim/bin:$PATH" sh ./scripts/test.sh

after_success:
  - coveralls
